x-common: &common
  image: "node:22.11.0"
  environment:
    - VITE_API_BASE_URL=http://dummy-server

pipeline:
  setup:
    <<: *common
    commands:
      - npm i -g npm@11.2.0
      - npm ci --prefer-offline --engine-strict
  js-prettier:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run prettier:check
  js-lint:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run lint
  js-test:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run test
